### ISSUE TITLE
ERROR: stDev has been finalized; can't insert() new value.

### ISSUE THREAD

**Issue by coreywischmeyer** [marbl/canu#263]
Hi, 

I stumbled into this error this morning and I'm not sure how to proceed. 

```
==> MERGE ORPHANS.

computeErrorProfiles()-- Computing error profiles for 61277 tigs, with 16 threads.
ERROR: stdDev has been finalized; can't insert() new value.
```

I've attached the complete log below.

[unitigger.err.txt](https://github.com/marbl/canu/files/508636/unitigger.err.txt)

**Comment by brianwalenz** [comment]
Which version (canu -version) is this?

Are you able to update and recompile?  I'll have to add some debugging a rerun is useful.  There is some compile-time debugging in there, but it would need a bunch of analysis confirm my suspicious, and I'd rather just code it in.

**Comment by coreywischmeyer** [comment]
`canu -version` returns:
`Canu v1.3 (+190 commits) r7806 aef501c84fe42b71d29e93cd5dc99db1d7d9f23e.`

This appears to be the current version.

I do have the ability to recompile, go ahead and make any necessary changes on your end and I'll be happy to get back to you with the results.

Thanks!

**Comment by brianwalenz** [comment]
Give the current code (gmake should report r7823) a shot.

Before compiling, change the two `#undef` lines at the top of src/bogart/AS_BAT_Unitig.C to `#define`.

To rerun, in unitigging/4-unitigger/, remove all the *.log files and run unitigger.sh.  From the log, it should run comfortable in 4gb memory.

I'm interested in the `*005*mergeOrphans*log` files.  These are probably large - drosophila generated about 3gb worth.  The last one (possibly two) will be most interesting.

**Comment by coreywischmeyer** [comment]
I've made the changes and recompiled and re-running it now. I see that it has already passed the point where it was crashing and the files you are interested in have been generated. What is the best way to get these into your hands? Perhaps through Dropbox?

Finally, would it be correct to restart the assembly using the original command to continue from unitigging?

**Comment by brianwalenz** [comment]
If it runs to completion now, I don't need anything.  There were a bunch of other changes that you got when you updated, and possibly I fixed whatever the problem was.

To restart, assuming you let this unitigger.sh run to completion, yes, just restart the same canu command.  It'll use the result you just computed.  If you kill unitigger.sh, the safest way to restart is to delete all of 4-unitigger/ and restart canu.  (Don't forget to disable that debugging)

If it is still failing, you can upload logs to ftp://ftp.cbcb.umd.edu/incoming/sergek, which is a write-only location.

**Comment by coreywischmeyer** [comment]
I misunderstood the first part and by changing the lines to \#define I was able to get through unitigging without issue. Now I'm having issues in consensus:

```
Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'failed to generate consensus.  Made 2 attempts, jobs still failed'.
```

I'll pull the changes, turn on debugging and recompile to see if that fixed this error too.

**Comment by coreywischmeyer** [comment]
Brian,

I've updated canu  ```Canu v1.3 (+207 commits) r7823 7324601c554ac342f24f0804a11a81502fd433c0.``` .

The build still fails at unitigging. I have uploaded a file called `mergeOrphans.tar.gz` to `ftp://ftp.cbcb.umd.edu/incoming/sergek`

**Comment by brianwalenz** [comment]
I think I found the problem, but I haven't been able to reproduce the flaw.  Give the latest a try.

**Comment by coreywischmeyer** [comment]
Alright so this time I made it to generating unitigs.

I also want to describe the data. I'm working with 1.2 million high-confidence reads with the n50 of 20kb and each read represents something like 60x coverage. I assumed this closest to corrected PacBio data. 

`Canu v1.3 (+217 commits) r7833 3320a316d9db860645d2a2edaad00cf789edfa4a.`

```bash
/genomics/shared/canu/canu/Linux-amd64/bin/canu -s run_canu.spec \ #CPU config nothing interesting here.
-trim-assemble \
-pacbio-corrected input.fna \
-p genome \
-d genome \
-genomeSize=1.8g
```

```
==> GENERATE UNITIGS.

splitDiscontinuous()-- Tested 23766 tigs, split 1164 tigs into 2740 new tigs.
AssemblyGraph()-- generating '/genomics-2/DATA/ASSEMBLY/ref_nigeria/canu/nigeria/unitigging/4-unitigger/nigeria.unitigs.gfa'.

Failed with 'Segmentation fault'

Backtrace (mangled):

/genomics/shared/canu/canu/Linux-amd64/bin/bogart(_Z17AS_UTL_catchCrashiP7siginfoPv+0x27)[0x521957]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xfcb0)[0x7f6f6a508cb0]
/genomics/shared/canu/canu/Linux-amd64/bin/bogart[0x506655]
/genomics/shared/canu/canu/Linux-amd64/bin/bogart[0x404e2b]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xed)[0x7f6f6a15c76d]
/genomics/shared/canu/canu/Linux-amd64/bin/bogart[0x405701]

Backtrace (demangled):

[0] /genomics/shared/canu/canu/Linux-amd64/bin/bogart::AS_UTL_catchCrash(int, siginfo*, void*) + 0x27  [0x521957]
[1] /lib/x86_64-linux-gnu/libpthread.so.0::(null) + 0xfcb0  [0x7f6f6a508cb0]
[2] /genomics/shared/canu/canu/Linux-amd64/bin/bogart() [0x506655]
[3] /genomics/shared/canu/canu/Linux-amd64/bin/bogart() [0x404e2b]
[4] /lib/x86_64-linux-gnu/libc.so.6::(null) + 0xed  [0x7f6f6a15c76d]
[5] /genomics/shared/canu/canu/Linux-amd64/bin/bogart() [0x405701]
```

**Comment by brianwalenz** [comment]
Yup, I saw a 60k 'read' in there.  Guessed it was something weird like this.

Not much to go on there.  Recompile with debugging symbols (gmake BUILDDEBUG=1) and the crash report should give line numbers.  Any chance you can share the data?  Either the reads themselves, or the gkpStore and ovlStore (preferred).

The 'unitig' code is very very new, and not strictly needed to get an assembly.  In fact, you already have the assembly in '*.ctgStore'.  You can _possibly_ force canu to run to completion by moving the ctgStore up one directory (to unitigging/*ctgStore), and then copying it to a similarly named utgStore.  Restarting canu should then proceed with generating consensus.

In any case, look in the 4-unitigger/*sizes files to see if you're getting contigs of decent size.

**Comment by coreywischmeyer** [comment]
Unfortunately I'm not able to share the data. Would it still be helpful if I were to re-run the re-compiled executable and upload the log files for you here?

**Comment by coreywischmeyer** [comment]
```
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'failed to generate consensus.  Made 2 attempts, jobs still failed'.
```

I'm beginning to think the error that caused the first problem is causing all of these subsequent issues.

Here is the segmentation fault in one of the output files. I'm going to delete unitigging and try again with the debug flags on and see what happens.

```
generatePBDAG()-- align read 332216 (79/80) at 160642-165291
generatePBDAG()-- aligned             distance=    6 size= 4651, 0.001290 < 0.075000
generatePBDAG()-- Exceeded band size max_k 3315 - min_k -1487 = 4802 > band_size = 4800.
generatePBDAG()-- retry with bandTolerance = 9600

Failed with 'Segmentation fault'

Backtrace (mangled):

/genomics/shared/canu/canu/Linux-amd64/bin/utgcns(_Z17AS_UTL_catchCrashiP7siginfoPv+0x27)[0x42ff87]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10330)[0x7f8615d78330]
/genomics/shared/canu/canu/Linux-amd64/bin/utgcns[0x468963]
/genomics/shared/canu/canu/Linux-amd64/bin/utgcns[0x440fb8]
/usr/lib/x86_64-linux-gnu/libgomp.so.1(+0x834a)[0x7f86161a434a]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8184)[0x7f8615d70184]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f8615a9d37d]

Backtrace (demangled):

[0] /genomics/shared/canu/canu/Linux-amd64/bin/utgcns::AS_UTL_catchCrash(int, siginfo*, void*) + 0x27  [0x42ff87]
[1] /lib/x86_64-linux-gnu/libpthread.so.0::(null) + 0x10330  [0x7f8615d78330]
[2] /genomics/shared/canu/canu/Linux-amd64/bin/utgcns() [0x468963]
[3] /genomics/shared/canu/canu/Linux-amd64/bin/utgcns() [0x440fb8]
[4] /usr/lib/x86_64-linux-gnu/libgomp.so.1::(null) + 0x834a  [0x7f86161a434a]
[5] /lib/x86_64-linux-gnu/libpthread.so.0::(null) + 0x8184  [0x7f8615d70184]
[6] /lib/x86_64-linux-gnu/libc.so.6::(null) + 0x6d  [0x7f8615a9d37d]

GDB:


Segmentation fault (core dumped)
```

**Comment by brianwalenz** [comment]
This will be hard to fix.

If it is still failing, recompile with (compiler) debug symbols (remove the Linux-amd64 directory then `gmake BUILDDEBUG=1`) and run this consensus job again (`sh utgcns.sh <number>`, where <number> is the number in the error file name).  That will at least tell me what line it is failing on.

You can also try modifying src/utgcns/unitigConsensus.C to disable the `while` loop on lines 383-393.  Add a line `#if 0` before the block, and a line `#endif` after the block.  This is trying to realign a read that failed to align.  Without the realign, the read is just dropped from consensus.

```
#if 0
    while ((aligned == false) && (bandTolerance < errorRate * (aLen + bLen))) {
      bandTolerance *= 4;
      fprintf(stderr, "generatePBDAG()-- retry with bandTolerance = %d\n",
              bandTolerance);
      aligned = NDalignment::align(aln.qstr.c_str(), aln.qstr.size(),
                                   aln.tstr.c_str(), aln.tstr.size(),
                                   bandTolerance,
                                   true,
                                   ndaln);

    }
#endif
```

**Comment by coreywischmeyer** [comment]
I went back to Canu v1.3 (+190 commits) r7806 aef501c84fe42b71d29e93cd5dc99db1d7d9f23e. 

Because I couldn't get unitigging to work and I got this error while running 5-consenus jobs.
```
generatePBDAG()-- retry with bandTolerance = 9600

Failed with 'Segmentation fault'

Backtrace (mangled):

/genomics/shared/canu/canu/Linux-amd64/bin/utgcns[0x421b14]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10330)[0x7ff4ff670330]
/genomics/shared/canu/canu/Linux-amd64/bin/utgcns[0x459a32]
/genomics/shared/canu/canu/Linux-amd64/bin/utgcns[0x437b5e]
/usr/lib/x86_64-linux-gnu/libgomp.so.1(+0x834a)[0x7ff4ffa9c34a]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8184)[0x7ff4ff668184]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7ff4ff39537d]

Backtrace (demangled):

[0] /genomics/shared/canu/canu/Linux-amd64/bin/utgcns() [0x421b14]
[1] /lib/x86_64-linux-gnu/libpthread.so.0::(null) + 0x10330  [0x7ff4ff670330]
[2] /genomics/shared/canu/canu/Linux-amd64/bin/utgcns() [0x459a32]
[3] /genomics/shared/canu/canu/Linux-amd64/bin/utgcns() [0x437b5e]
[4] /usr/lib/x86_64-linux-gnu/libgomp.so.1::(null) + 0x834a  [0x7ff4ffa9c34a]
[5] /lib/x86_64-linux-gnu/libpthread.so.0::(null) + 0x8184  [0x7ff4ff668184]
[6] /lib/x86_64-linux-gnu/libc.so.6::(null) + 0x6d  [0x7ff4ff39537d]

GDB:


consensus.sh: line 66: 23888 Segmentation fault      (core dumped)
```

Then I updated to the latest build hoping consensus would work and got:

```
generatePBDAG()-- retry with bandTolerance = 9600

Failed with 'Segmentation fault'

Backtrace (mangled):

/genomics/shared/canu/canu/Linux-amd64/bin/utgcns[0x421bfc]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10330)[0x7f42ab99f330]
/genomics/shared/canu/canu/Linux-amd64/bin/utgcns[0x459d7c]
/genomics/shared/canu/canu/Linux-amd64/bin/utgcns[0x437ea8]
/usr/lib/x86_64-linux-gnu/libgomp.so.1(+0x834a)[0x7f42abdcb34a]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8184)[0x7f42ab997184]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f42ab6c437d]

Backtrace (demangled):

[0] /genomics/shared/canu/canu/Linux-amd64/bin/utgcns() [0x421bfc]
[1] /lib/x86_64-linux-gnu/libpthread.so.0::(null) + 0x10330  [0x7f42ab99f330]
[2] /genomics/shared/canu/canu/Linux-amd64/bin/utgcns() [0x459d7c]
[3] /genomics/shared/canu/canu/Linux-amd64/bin/utgcns() [0x437ea8]
[4] /usr/lib/x86_64-linux-gnu/libgomp.so.1::(null) + 0x834a  [0x7f42abdcb34a]
[5] /lib/x86_64-linux-gnu/libpthread.so.0::(null) + 0x8184  [0x7f42ab997184]
[6] /lib/x86_64-linux-gnu/libc.so.6::(null) + 0x6d  [0x7f42ab6c437d]

GDB:


consensus.sh: line 66: 30307 Segmentation fault      (core dumped)
```

I ran make: `make -j 40 BUILDDEBUG=1`

**Comment by brianwalenz** [comment]
Have you tried disabling the 'bandTolerance' block as I suggested previously?  I still see it enabled in both attempts.

**Comment by coreywischmeyer** [comment]
My apologies, I've done the following now:

* updated canu to today's version
* commented out bandTolerance
* added `#defined` to the debug variables.
* make BUILDDEBUG=1

```
BestOverlapGraph()-- removing best edges for contained reads.

==> BUILDING GREEDY TIGS.

breakSingletonTigs()-- Removed 55631 singleton tigs; reads are now unplaced.

==> PLACE CONTAINED READS.

computeErrorProfiles()-- Computing error profiles for 73858 tigs, with 10 threads.

Failed with 'Segmentation fault'

Backtrace (mangled):

/genomics/shared/canu/Linux-amd64/bin/bogart[0x4c09d0]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10330)[0x7fc2307f4330]
/genomics/shared/canu/Linux-amd64/bin/bogart[0x4af1b1]
/genomics/shared/canu/Linux-amd64/bin/bogart[0x4ae56f]
/genomics/shared/canu/Linux-amd64/bin/bogart[0x4ae3b8]
/genomics/shared/canu/Linux-amd64/bin/bogart[0x4048fe]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7fc230440f45]
/genomics/shared/canu/Linux-amd64/bin/bogart[0x4029f9]

Backtrace (demangled):

[0] /genomics/shared/canu/Linux-amd64/bin/bogart() [0x4c09d0]
[1] /lib/x86_64-linux-gnu/libpthread.so.0::(null) + 0x10330  [0x7fc2307f4330]
[2] /genomics/shared/canu/Linux-amd64/bin/bogart() [0x4af1b1]
[3] /genomics/shared/canu/Linux-amd64/bin/bogart() [0x4ae56f]
[4] /genomics/shared/canu/Linux-amd64/bin/bogart() [0x4ae3b8]
[5] /genomics/shared/canu/Linux-amd64/bin/bogart() [0x4048fe]
[6] /lib/x86_64-linux-gnu/libc.so.6::(null) + 0xf5  [0x7fc230440f45]
[7] /genomics/shared/canu/Linux-amd64/bin/bogart() [0x4029f9]

GDB:


Segmentation fault (core dumped)
```

**Comment by brianwalenz** [comment]
I think I fixed this, give the latest a try.
