### ISSUE TITLE
canu failed with 'failed to compute mhap overlaps. segmentation fault'

### ISSUE THREAD

**Issue by kullrich** [marbl/canu#662]
Hi, I am assembling mouse genomes with PacBio Sequel data.

I am running in a similar issue like #417, however, removing the correction/1-overlapper/results/ and re-run canu did not solve my problem.

Here is the canu version that I am using:
```
Canu 1.6
```
Here is the running command:
```
canu -correct -p 2410-e-default -d 2410-e-correct-default genomeSize=2.75g useGrid=true gridEngine=slurm gridOptionsJobName=24e maxThreads=24 maxMemory=256g correctedErrorRate=0.15 gridOptions="-t 144:00:00" -pacbio-raw 2410-e.all.subreads.bam.fastq
```
Here is the problem as you know already:
 ```
-- Detected Java(TM) Runtime Environment '1.8.0_121' (from '/data/modules/java/x64/jdk1.8.0_121/bin/java').
-- Detected gnuplot version '4.6 patchlevel 2' (from 'gnuplot') and image format 'png'.
-- Detected 32 CPUs and 504 gigabytes of memory.
-- Limited to 256g gigabytes from maxMemory option.
-- Limited to 24 CPUs from maxThreads option.
-- Detected Slurm with 'MaxArraySize' limited to 25000 jobs.
-- 
-- Found  20 hosts with  32 cores and  503 GB memory under Slurm control.
-- Found   2 hosts with  48 cores and 1510 GB memory under Slurm control.
-- Found   8 hosts with  28 cores and  125 GB memory under Slurm control.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl    125 GB   16 CPUs  (k-mer counting)
-- Grid:  cormhap   17 GB    4 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    16 GB    4 CPUs  (overlap detection)
-- Grid:  utgovl    16 GB    4 CPUs  (overlap detection)
-- Grid:  cor       17 GB    4 CPUs  (read correction)
-- Grid:  ovb        4 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       32 GB    1 CPU   (overlap store sorting)
-- Grid:  red       16 GB    4 CPUs  (read error detection)
-- Grid:  oea        4 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      251 GB   16 CPUs  (contig construction)
-- Grid:  cns      125 GB    8 CPUs  (consensus)
-- Grid:  gfa       32 GB    8 CPUs  (GFA alignment and processing)
--
-- Found PacBio uncorrected reads in 'correction/2410-e-default.gkpStore'.
--
-- Generating assembly '2410-e-default' in '/home/ullrich/scratch/pacbio/2410-e/2410-e-correct-default'
--
-- Parameters:
--
--  genomeSize        2750000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.1500 ( 15.00%)
--    utgOvlErrorRate 0.1500 ( 15.00%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.1500 ( 15.00%)
--    utgErrorRate    0.1500 ( 15.00%)
--    cnsErrorRate    0.1500 ( 15.00%)
--
--
-- BEGIN CORRECTION
--
--
-- Mhap overlap jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/results/000001.ovb FAILED.
```
Here is one problematic output:
```
Fetch blocks/000162.dat
Fetch blocks/000163.dat
Fetch blocks/000164.dat
Fetch blocks/000165.dat
Fetch blocks/000166.dat

Running block 000096 in query 000354

/var/spool/slurmd/job1103572/slurm_script: line 4962:  8383 Segmentation fault      (core dumped) $bin/mhapConvert -G ../2410-e-default.gkpStore $cvt -o ./results/$qry.mhap.ovb.WORKING ./results/$qry.mhap
```

I have not tried to use e.g. 'minamp' for the cor step, but I will start this now, maybe you know any solutions for that issue or how to track the Segmentation fault. I don't think that the issue is about one compute node having not loaded e.g. perl or java, since after deleting the .WORKING files other nodes are active to calculate them.

Thank you in anticipation

Kristian Ullrich

**Comment by skoren** [comment]
Have you tried completely removing the 1-overlapper folder and re-running? This sounds like the precompute step had a write error and is corrupting the input for this step. What's the output in the offending job file (mhap.000001.out)?

**Comment by skoren** [comment]
I'll assume this is resolved due to inactivity. The latest code in tip doesn't do the read ID conversion that was causing bad overlaps as well.

**Comment by kullrich** [comment]
Actually Not resolved yet. Our Cluster is just too busy so that the canu job is still in the queing.
I will give Feedback once the job has finished.
If this is not functional with default overlap algorithm I will use the one from 1.5 there it worked just fine.
Best regards 

Kristian Ullrich, Ph.D.
Department of Evolutionary Genetics
Max Planck Institute for Evolutionary Biology
August Thienemann Str. 2
24306 Ploen
Germany
+49 4522 763 274
ullrich@evolbio.mpg.de

----- Ursprüngliche Mail -----
Von: Sergey Koren <notifications@github.com>
An: marbl/canu <canu@noreply.github.com>
CC: Kristian Ullrich <ullrich@evolbio.mpg.de>, Author <author@noreply.github.com>
Gesendet: Fri, 20 Oct 2017 17:53:25 +0200 (CEST)
Betreff: Re: [marbl/canu] canu failed with 'failed to compute mhap overlaps. segmentation fault' (#662)

I'll assume this is resolved due to inactivity. The latest code in tip doesn't do the read ID conversion that was causing bad overlaps as well.
