### ISSUE TITLE
Bogart Failed

### ISSUE THREAD

**Issue by Erin-Vaughn** [marbl/canu#961]
I'm running the following command:
canu -p Non-Branching7runs -d ~/assemblies/Non-Branching7runs genomeSize=300m maxThreads=30 -nanopore-raw Allruns_highQuality-reads.fastq.gz 

Bogart is failing. I've restarted twice, removing maxThreads=30 the second time. 

I've attached the unitigger.err file here: [unitigger_err.txt](https://github.com/marbl/canu/files/2109608/unitigger_err.txt)

unitigger.000001.out gives:
```
Running job 1 based on command line options.
./unitigger.sh: 86: ./unitigger.sh: cannot create ../Non-Branching7runs.ctgStore/seqDB.v001.sizes.txt: Directory nonexistent
```
The last bit of the stdout shows the following:
```
-- BEGIN ASSEMBLY
--
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'bat' concurrent execution on Mon Jun 18 10:08:13 2018 with 11394.202 GB free disk space (1 processes; 7 concurrently)

    cd unitigging/4-unitigger
    ./unitigger.sh 1 > ./unitigger.000001.out 2>&1

-- Finished on Mon Jun 18 10:16:20 2018 (487 seconds) with 11393.794 GB free disk space
----------------------------------------
--
-- Bogart failed, retry
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'bat' concurrent execution on Mon Jun 18 10:16:20 2018 with 11393.794 GB free disk space (1 processes; 7 concurrently)

    cd unitigging/4-unitigger
    ./unitigger.sh 1 > ./unitigger.000001.out 2>&1

-- Finished on Mon Jun 18 10:26:13 2018 (593 seconds) with 11392.942 GB free disk space
----------------------------------------
--
-- Bogart failed, tried 2 times, giving up.
--

ABORT:
ABORT: Canu snapshot v1.5 +154 changes (r8354 5e082e7ce553532e47aca7aec576bb9fc53a4809)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```

**Comment by Erin-Vaughn** [comment]
I realised that I was running v1.5. I updated to v1.7 and restarted but now I'm getting this:

-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_171' (from 'java').
-- Detected gnuplot version '4.6 patchlevel 6' (from 'gnuplot') and image format 'png'.
-- Detected 56 CPUs and 1008 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |     total usage     algorithm
--        -------  ------  --------   --------  -----------------  -----------------------------
-- Local: meryl     64 GB   16 CPUs x   1 job     64 GB   16 CPUs  (k-mer counting)
-- Local: cormhap   13 GB   14 CPUs x   4 jobs    52 GB   56 CPUs  (overlap detection with mhap)
-- Local: obtovl     8 GB    8 CPUs x   7 jobs    56 GB   56 CPUs  (overlap detection)
-- Local: utgovl     8 GB    8 CPUs x   7 jobs    56 GB   56 CPUs  (overlap detection)
-- Local: ovb        4 GB    1 CPU  x  56 jobs   224 GB   56 CPUs  (overlap store bucketizer)
-- Local: ovs       16 GB    1 CPU  x  56 jobs   896 GB   56 CPUs  (overlap store sorting)
-- Local: red        8 GB    4 CPUs x  14 jobs   112 GB   56 CPUs  (read error detection)
-- Local: oea        4 GB    1 CPU  x  56 jobs   224 GB   56 CPUs  (overlap error adjustment)
-- Local: bat       64 GB    8 CPUs x   1 job     64 GB    8 CPUs  (contig construction)
-- Local: gfa        8 GB    8 CPUs x   1 job      8 GB    8 CPUs  (GFA alignment and processing)
--
-- In 'Non-Branching7runs.gkpStore', found Nanopore reads:
--   Raw:        3484292
--   Corrected:  0
--   Trimmed:    0
--
-- Generating assembly 'Non-Branching7runs' in '/home/erin/assemblies/Non-Branching7runs'
--
-- Parameters:
--
--  genomeSize        300000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1440 ( 14.40%)
--    utgOvlErrorRate 0.1440 ( 14.40%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1440 ( 14.40%)
--    utgErrorRate    0.1440 ( 14.40%)
--    cnsErrorRate    0.1920 ( 19.20%)
--
--
-- BEGIN ASSEMBLY
--
-- Unable to assemble uncorrected reads.

ABORT:
ABORT: Canu 1.7
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   unable to assemble uncorrected reads.
ABORT:

**Comment by brianwalenz** [comment]
Did you restart from scratch, or try to resume the existing assembly?  It's not possible to resume, unfortunately, but you can 'resume' from the trimmed reads with something like
```
canu <options-and-what-not> -assemble -nanopore-corrected <old-assembly>/*.trimmedReads.fasta.gz
```

**Comment by Erin-Vaughn** [comment]
I first re-ran the same command, which failed.

Then I ran:
`canu -p Non-Branching7runs -d ~/assemblies/Non-Branching7runs genomeSize=300m -assemble -nanopore-corrected Non-Branching7runs.trimmedReads.fasta.gz`

The failure looks as above either way. Did I screw it by re-running the original command?

**Comment by brianwalenz** [comment]
The new run needs a different -d directory.  Otherwise, it tried to reuse the old data and gets confused.

**Comment by Erin-Vaughn** [comment]
I resumed from the trimmed reads with:
canu -p Non-Branching7runs -d ~/assemblies/Non-Branching7runs_1.7 genomeSize=300m -assemble -nanopore-corrected Non-Branching7runs.trimmedReads.fasta.gz 

It failed at the same point as in my original post. Any ideas?

**Comment by brianwalenz** [comment]
What is shown in unitigger.err?

We just made a 1.7.1 patch release with lots of bugfixes in this area.  Try that.  There are no binaries at the moment though.

**Comment by Erin-Vaughn** [comment]
Here's my unitigger.err file:

[unitigger.err.txt](https://github.com/marbl/canu/files/2126367/unitigger.err.txt)

Is there a way to execute beginning with the bogart step? The last 'resume' from the trimmed reads took 4 days to get through to the bogart failure.

**Comment by brianwalenz** [comment]
That should definitely be fixed in 1.7.1.  Just download, compile it and restart with the new version.  It will resume at this step.

**Comment by Erin-Vaughn** [comment]
Nope. I'm still getting the same failure.

[unitigger.err.txt](https://github.com/marbl/canu/files/2126511/unitigger.err.txt)

**Comment by brianwalenz** [comment]
That's still the 1.7 release, not 1.7.1.

**Comment by Erin-Vaughn** [comment]
My system admin assures me that it is indeed 1.7.1 but that you've not updated the version number.

**Comment by brianwalenz** [comment]
True, the version number didn't change.

The error, as reported, can only occur in 1.7.

**Comment by skoren** [comment]
Any updates on this?

**Comment by Erin-Vaughn** [comment]
I've not been able to get past the previously described error. I'm planning to run it on a more powerful system in hopes that I'm simply lacking in computational power.

**Comment by skoren** [comment]
A bigger machine won't help since you're encountering a known bug. The latest 1.7.1 code will properly report version. Can you make sure you have it installed, remove the ```unitigging/4-unitigger``` folder and re-run 1.7.1 to see if it completes.

**Comment by Erin-Vaughn** [comment]
My system admin would like to check if we have the correct version installed. Could you please provide the version string that should print if we have 1.7.1 installed correctly?

**Comment by skoren** [comment]
It should report 1.7.1:
```
canu-1.7.1/Linux-amd64/bin/canu -version
Canu snapshot v1.7.1 +0 changes (r8698 dfa60b83414f8df5233972c972cad75ff6f16384)
```

**Comment by brianwalenz** [comment]
Success?

**Comment by skoren** [comment]
Inactive, closing.
